## Data Reading

### CSV Files

In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName("Citibike Analysis").getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/06/25 21:15:59 WARN Utils: Your hostname, pius-home, resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
26/06/25 21:15:59 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/06/25 21:15:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
spark.read.format("csv").option("inferSchema", True).option("header", True).load(
    "/home/piusm/dev-projects/analytics-engineering/Spark/data/JC-202102-citibike-tripdata.csv"
)

DataFrame[ride_id: string, rideable_type: string, started_at: timestamp, ended_at: timestamp, start_station_name: string, start_station_id: string, end_station_name: string, end_station_id: string, start_lat: double, start_lng: double, end_lat: double, end_lng: double, member_casual: string]

In [4]:
df_202102 = spark.read.csv(
    "/home/piusm/dev-projects/analytics-engineering/Spark/data/JC-202102-citibike-tripdata.csv",
    inferSchema=True,
    header=True,
)

In [5]:
df_202102.show()

+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+
|         ride_id|rideable_type|         started_at|           ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|start_lat| start_lng|          end_lat|           end_lng|member_casual|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+
|121DD7DD23CB1335|  docked_bike|2021-02-03 23:11:28|2021-02-03 23:18:28|Hoboken Ave at Mo...|           JC105|     Christ Hospital|         JC034|40.735208|-74.046964|        40.734786|        -74.050444|       member|
|FD73FB85F008349D|  docked_bike|2021-02-27 16:34:05|2021-02-27 16:56:40|        Newport Pkwy|           JC008|    Marin Light Rail|         JC013|40.728744|-74.032108|40.71458403535893|-74.04281705617905|       member|
|39F9E6663CB5FDF6|  docked_bike|2021-02-26 23:16:04|2021-02-26 23:22:25|      Journal Square|           JC103|Baldwin at Montgo...|         JC020| 40.73367|  -74.0625|       40.7236589|       -74.0641943|       member|
|A64745CB0792EC6F|  docked_bike|2021-02-24 16:51:50|2021-02-24 17:16:09|Hoboken Ave at Mo...|           JC105|Hoboken Ave at Mo...|         JC105|40.735208|-74.046963|40.73520838045357|-74.04696375131607|       casual|
|75CC76EB9543764A|  docked_bike|2021-02-24 20:44:16|2021-02-24 20:44:46|Hoboken Ave at Mo...|           JC105|Hoboken Ave at Mo...|         JC105|40.735208|-74.046963|40.73520838045357|-74.04696375131607|       member|
|9E512D211620A136|  docked_bike|2021-02-12 20:03:24|2021-02-12 20:18:34|        Newport Pkwy|           JC008|         Paulus Hook|         JC002|40.728744|-74.032108|       40.7141454|       -74.0335519|       casual|
|381EF1361C1A6DB8|  docked_bike|2021-02-16 19:39:39|2021-02-16 19:41:59|          Newark Ave|           JC032|    Monmouth and 6th|         JC075|40.721525|-74.046305|        40.725685|         -74.04879|       member|
|928FA29F84E99326|  docked_bike|2021-02-12 18:14:07|2021-02-12 18:19:49|        Newport Pkwy|           JC008|           Warren St|         JC006|40.728744|-74.032108|       40.7211236|      -74.03805095|       member|
|A7E2FCAC8E229A75|  docked_bike|2021-02-16 05:17:11|2021-02-16 05:22:09|        Newport Pkwy|           JC008|           Warren St|         JC006|40.728744|-74.032108|       40.7211236|      -74.03805095|       member|
|A591312D7A1533DD|  docked_bike|2021-02-10 11:44:47|2021-02-10 11:52:30|        Newport Pkwy|           JC008|           Warren St|         JC006|40.728744|-74.032108|       40.7211236|      -74.03805095|       member|
|DA917A5A770BB921|  docked_bike|2021-02-25 05:55:02|2021-02-25 06:01:45|Hoboken Ave at Mo...|           JC105|        Newport PATH|         JC066|40.735208|-74.046963|       40.7272235|       -74.0337589|       casual|
|91EE894EDB054D1D|  docked_bike|2021-02-25 14:22:40|2021-02-25 15:05:18|Hoboken Ave at Mo...|           JC105|        Newport PATH|         JC066|40.735208|-74.046963|       40.7272235|       -74.0337589|       member|
|00BA19D55F5C4D5F|  docked_bike|2021-02-27 15:44:07|2021-02-27 15:59:40|        Newport Pkwy|           JC008|      Van Vorst Park|         JC035|40.728744|-74.032108|      40.71848892|     -74.047726625|       member|
|C29080C1B25BF636|  docked_bike|2021-02-17 16:06:36|2021-02-17 16:08:58|   5 Corners Library|           JC018|             Hilltop|         JC019|40.734961|-74.059503|       40.7311689|       -74.0575736|       member|
|8E3741BD012732D8|  docked_bike|2021-02-16 19:46:39|2021-02-16 19:56:24|          Newark Ave|           JC032|            Grand St|         JC102|40.721525|-74.046305|        40.715178|        -74.037683|       member|
|532195C2DDA105CE|  docked_bike|2021-02-16 13:36:42|2021-02-16 14:03:05|        Newport Pkwy|           JC008|     Jersey & 6th St|         JC027|40.728744|-74.032108|40.72528910781132|-74.04557168483734|       member|
|ECCEA934882DE00C|  docked_bike|2021-02-07 22:58:13|2021-02-07 23:07:55|        Newport Pkwy|           JC008|     Jersey & 6th St|         JC027|40.728744|-74.032108|40.72528910781132|-74.04557168483734|       casual|
|75334C6D460251F0|  docked_bike|2021-02-24 18:38:05|2021-02-24 18:45:14|   5 Corners Library|           JC018|        Brunswick St|         JC023|40.734961|-74.059503|       40.7241765|       -74.0506564|       member|
|4214A9E07D15C564|  docked_bike|2021-02-15 13:00:21|2021-02-15 13:09:05|      Journal Square|           JC103|        Lincoln Park|         JC053| 40.73367|  -74.0625| 40.7246050998869|-74.07840594649315|       casual|
|533977109CABC060|  docked_bike|2021-02-25 21:49:44|2021-02-25 21:59:03|       Washington St|           JC098|    Marin Light Rail|         JC013|40.724294|-74.035483|        40.714584|        -74.042817|       member|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+
only showing top 20 rows

In [6]:
df_202102.limit(10).toPandas()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
5,9E512D211620A136,docked_bike,2021-02-12 20:03:24,2021-02-12 20:18:34,Newport Pkwy,JC008,Paulus Hook,JC002,40.728744,-74.032108,40.714145,-74.033552,casual
6,381EF1361C1A6DB8,docked_bike,2021-02-16 19:39:39,2021-02-16 19:41:59,Newark Ave,JC032,Monmouth and 6th,JC075,40.721525,-74.046305,40.725685,-74.048790,member
7,928FA29F84E99326,docked_bike,2021-02-12 18:14:07,2021-02-12 18:19:49,Newport Pkwy,JC008,Warren St,JC006,40.728744,-74.032108,40.721124,-74.038051,member
8,A7E2FCAC8E229A75,docked_bike,2021-02-16 05:17:11,2021-02-16 05:22:09,Newport Pkwy,JC008,Warren St,JC006,40.728744,-74.032108,40.721124,-74.038051,member
9,A591312D7A1533DD,docked_bike,2021-02-10 11:44:47,2021-02-10 11:52:30,Newport Pkwy,JC008,Warren St,JC006,40.728744,-74.032108,40.721124,-74.038051,member

### JSON Files

In [10]:
json_file = (
    spark.read.format("json")
    .option("inferSchema", True)
    .option("header", True)
    .option("multiLine", False)
    .load("/home/piusm/dev-projects/analytics-engineering/Spark/data/drivers.json")
)

In [12]:
json_file.limit(10).toPandas()

,code,dob,driverId,driverRef,name,nationality,number,url
0,HAM,1985-01-07,1,hamilton,"(Lewis, Hamilton)",British,44,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,HEI,1977-05-10,2,heidfeld,"(Nick, Heidfeld)",German,\N,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,ROS,1985-06-27,3,rosberg,"(Nico, Rosberg)",German,6,http://en.wikipedia.org/wiki/Nico_Rosberg
3,ALO,1981-07-29,4,alonso,"(Fernando, Alonso)",Spanish,14,http://en.wikipedia.org/wiki/Fernando_Alonso
4,KOV,1981-10-19,5,kovalainen,"(Heikki, Kovalainen)",Finnish,\N,http://en.wikipedia.org/wiki/Heikki_Kovalainen
5,NAK,1985-01-11,6,nakajima,"(Kazuki, Nakajima)",Japanese,\N,http://en.wikipedia.org/wiki/Kazuki_Nakajima
6,BOU,1979-02-28,7,bourdais,"(Sébastien, Bourdais)",French,\N,http://en.wikipedia.org/wiki/S%C3%A9bastien_Bo...
7,RAI,1979-10-17,8,raikkonen,"(Kimi, Räikkönen)",Finnish,7,http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C...
8,KUB,1984-12-07,9,kubica,"(Robert, Kubica)",Polish,88,http://en.wikipedia.org/wiki/Robert_Kubica
9,GLO,1982-03-18,10,glock,"(Timo, Glock)",German,\N,http://en.wikipedia.org/wiki/Timo_Glock

### Schema Definition

In [13]:
df_202102.printSchema()

root
 |-- ride_id: string (nullable = true)
 |-- rideable_type: string (nullable = true)
 |-- started_at: timestamp (nullable = true)
 |-- ended_at: timestamp (nullable = true)
 |-- start_station_name: string (nullable = true)
 |-- start_station_id: string (nullable = true)
 |-- end_station_name: string (nullable = true)
 |-- end_station_id: string (nullable = true)
 |-- start_lat: double (nullable = true)
 |-- start_lng: double (nullable = true)
 |-- end_lat: double (nullable = true)
 |-- end_lng: double (nullable = true)
 |-- member_casual: string (nullable = true)

In [20]:
main_schema = """
    ride_id string, 
    rideable_type string,
    started_at timestamp,
    ended_at timestamp,
    start_station_name string, 
    start_station_id string,
    end_station_name string,
    end_station_id string,
    start_lat double,
    start_lng double,
    end_lat double,
    end_lng double,
    member_casual string
"""

In [21]:
df_202103 = (
    spark.read.format("csv")
    .schema(main_schema)
    .option("header", True)
    .load(
        "/home/piusm/dev-projects/analytics-engineering/Spark/data/JC-202103-citibike-tripdata.csv"
    )
)

In [22]:
df_202103.printSchema()

root
 |-- ride_id: string (nullable = true)
 |-- rideable_type: string (nullable = true)
 |-- started_at: timestamp (nullable = true)
 |-- ended_at: timestamp (nullable = true)
 |-- start_station_name: string (nullable = true)
 |-- start_station_id: string (nullable = true)
 |-- end_station_name: string (nullable = true)
 |-- end_station_id: string (nullable = true)
 |-- start_lat: double (nullable = true)
 |-- start_lng: double (nullable = true)
 |-- end_lat: double (nullable = true)
 |-- end_lng: double (nullable = true)
 |-- member_casual: string (nullable = true)

#### StructType() - Programmatic way to define schema

In [24]:
from pyspark.sql.types import *
from pyspark.sql.functions import *

In [ ]:
main_schema = """
    ride_id string, 
    rideable_type string,
    started_at timestamp,
    ended_at timestamp,
    start_station_name string, 
    start_station_id string,
    end_station_name string,
    end_station_id string,
    start_lat double,
    start_lng double,
    end_lat double,
    end_lng double,
    member_casual string
"""

In [ ]:
my_struct_schema = StructType([
    StructField('ride_id', StringType(), True),
    StructField('rideably_type', StringType(), True),
    StructField('started_at', TimestampType(), True),
    StructField('ended_at', TimestampType(), True),
    StructField('start_station_name', StringType(), True),
    StructType('start_station_id', StringType(), False),
    StructType('end_station_name', StringType(), True),
    StructType()
    
])